### ISSUE TITLE
Expandir Conteúdo para Módulo Ciência de Dados com Python (2023)

### ISSUE THREAD

**Issue by storopoli** [storopoli/ciencia-de-dados#39]
Total 12 aulas.
1 aula introdutória e 1 aula de conclusão/encerramento.

## Numpy (3 aulas)

- [ ] Aula 6a - Por quê Algebra Linear é importante
- [ ] Aula 6b - NumPy NDArrays, criação, manipulação e transformações
- [ ] Aula 6c - NumPy Números Aleatórios e Estatística

## Pandas (4 aulas)

- [ ] Alinhar datasets com @wonderalexandre (titanic e pelo menos mais 1 com série temporal)
- [ ] Aula 7a - Pandas I/O, `Dataframe` e `Series`
- [ ] Aula 7b - filtragem e manipulações básicas
- [ ] Aula 7c - groupby, sumarizações, pivot table e crosstabs
- [ ] Aula 7d - Séries Temporais e funções de date e time series

## Matplotlib (3 aulas)

- [ ] Usar os mesmos datasets de Pandas
- [ ] Aula 8a - Plots disponíveis e guidelines gerais das funções `plt.*`
- [ ] Aula 8b - Subplots
- [ ] Aula 8c - Customizações

**Comment by fabianojd** [comment]
👋👏
