### ISSUE TITLE
Erro de digitação na Aula_7_pandas.ipynb (Importar Dados)

### ISSUE THREAD

**Issue by EdsonMSouza** [storopoli/ciencia-de-dados#4]
No texto abaixo a palavra **primeira** está com um "m" a mais.
Use o pd.read_csv() para importar os dados, use o argumento index_col=0 para que a **primmeira** coluna (modelo) seja os índices do DataFrame

**Comment by storopoli** [comment]
Arrumado pelo #5 valeu!
